{% include 'misc/header.py' %}
addons:
  chrome: stable # https://docs.travis-ci.com/user/chrome

dist: trusty # Chrome driver fails if not trusty dist

notifications:
  email: # sent to the committer and the author
    on_success: never # default: always
    on_failure: always # default: always

# Selenium webdriver for Chrome fails if not on sudo
# - see https://github.com/travis-ci/travis-ci/issues/8836
sudo: true

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
  - {{ cookiecutter.database }}
  - redis
  - rabbitmq

{%- if cookiecutter.database == "postgresql" %}
addons:
  postgresql: "9.6"
{%- endif %}

env:
  global:
    - E2E="yes"
    - E2E_OUTPUT="base64"
  matrix:
    - REQUIREMENTS=prod
    - REQUIREMENTS=qa

python:
  - "3.6"

before_install:
  {%- if cookiecutter.elasticsearch == "5" %}
  {%- set elasticsearch_test_version = "5.6.4" %}
  {%- elif cookiecutter.elasticsearch == "6" %}
  {%- set elasticsearch_test_version = "6.2.2" %}
  {%- endif %}
  - mkdir /tmp/elasticsearch
  - wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_test_version }}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - "/tmp/elasticsearch/bin/elasticsearch > /tmp/local-es.log &"
  # Gecko webdriver: https://github.com/mozilla/geckodriver/releases/
  - "PATH=$PATH:$HOME/webdrivers"
  - "if [ ${E2E} == 'yes' ] && [ ! -f $HOME/webdrivers/chromedriver ]; then wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip -P $HOME/webdrivers; unzip -d $HOME/webdrivers $HOME/webdrivers/chromedriver_linux64.zip; fi"
  - "nvm install 6; nvm use 6"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "cat requirements.txt > .travis-prod-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-qa-requirements.txt"
  - "./scripts/bootstrap"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

before_script:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "export E2E_WEBDRIVER_BROWSERS='Chrome'"
  - "if [ ${E2E} == 'yes' ]; then sh -e /etc/init.d/xvfb start; sleep 5; fi"
  # Allow ES to start
  - sleep 10
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200 && echo "Elasticsearch is up!" || cat /tmp/local-es.log

script:
  - ./run-tests.sh # E2E tests are skipped if E2E env is set to 'no'

after_success:
  - coveralls
