{% include 'misc/header.py' %}
version: '2.3'
services:
  app:
    build:
      context: ./
      args:
        - ENVIRONMENT=DEV
    image: {{cookiecutter.project_shortname}}
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['es:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      {%- if cookiecutter.database == 'postgresql'%}
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://{{cookiecutter.project_shortname}}:{{cookiecutter.project_shortname}}@db/{{cookiecutter.project_shortname}}"
      {%- elif cookiecutter.database == 'mysql'%}
      - "INVENIO_SQLALCHEMY_DATABASE_URI=mysql+pymysql://{{cookiecutter.project_shortname}}:{{cookiecutter.project_shortname}}@db/{{cookiecutter.project_shortname}}"
      {%- endif %}
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
  lb:
    build: ./docker/haproxy/
    image: {{cookiecutter.project_shortname}}-lb
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
  frontend:
    build: ./docker/nginx/
    image: {{cookiecutter.project_shortname}}-frontend
    restart: "always"
    ports:
      - "80"
      - "443"
  cache:
    image: redis
    restart: "always"
    read_only: true
    ports:
      - "6379:6379"
  db:
    {%- if cookiecutter.database == 'postgresql'%}
    image: postgres:9.6
    restart: "always"
    environment:
      - "POSTGRES_USER={{cookiecutter.project_shortname}}"
      - "POSTGRES_PASSWORD={{cookiecutter.project_shortname}}"
      - "POSTGRES_DB={{cookiecutter.project_shortname}}"
    ports:
      - "5432:5432"
    {%- elif cookiecutter.database == 'mysql'%}
    image: mysql
    restart: "always"
    environment:
      - "MYSQL_ROOT_PASSWORD={{cookiecutter.project_shortname}}"
      - "MYSQL_DATABAE={{cookiecutter.project_shortname}}"
      - "MYSQL_USER={{cookiecutter.project_shortname}}"
      - "MYSQL_PASSWORD={{cookiecutter.project_shortname}}"
    ports:
      - "3306:3306"
    {%- endif %}
  mq:
    image: rabbitmq:3-management
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
  es:
    {%- if cookiecutter.elasticsearch == '7' %}
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    {%- elif cookiecutter.elasticsearch == '6' %}
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
    {%- endif %}
    restart: "always"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    {%- if cookiecutter.elasticsearch == '7'%}
    image: docker.elastic.co/kibana/kibana-oss:7.2.0
    {%- elif cookiecutter.elasticsearch == '6' %}
    image: docker.elastic.co/kibana/kibana-oss:6.6.0
    {%- endif %}
    environment:
      - "ELASTICSEARCH_HOSTS=http://es:9200"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "5601:5601"
  flower:
    image: mher/flower
    command: --broker=amqp://guest:guest@mq:5672/ --broker_api=http://guest:guest@mq:15672/api/
    ports:
      - "5555:5555"
