# This is the dockerfile for your python dependencies only
{% include 'misc/header.py' %}
# docker invenio image
FROM inveniosoftware/centos7-python:3.6

COPY Pipfile Pipfile.lock ./
RUN pipenv install --deploy --system
