version: '2.3'
services:
  app:
    build:
      context: ./
      args:
        - ENVIRONMENT=DEV
    image: {{cookiecutter.project_shortname}}
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['es:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://{{cookiecutter.project_shortname}}:{{cookiecutter.project_shortname}}@db/{{cookiecutter.project_shortname}}"
      - "INVENIO_WSGI_PROXIES=2"
  lb:
    build: ./docker/haproxy/
    image: {{cookiecutter.project_shortname}}-lb
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
  frontend:
    build: ./docker/nginx/
    image: {{cookiecutter.project_shortname}}-frontend
    restart: "always"
    ports:
      - "80"
      - "443"
  cache:
    image: redis
    restart: "always"
    read_only: true
    ports:
      - "6379:6379"
  db:
    image: postgres:9.6
    restart: "always"
    environment:
      - "POSTGRES_USER={{cookiecutter.project_shortname}}"
      - "POSTGRES_PASSWORD={{cookiecutter.project_shortname}}"
    ports:
      - "5432:5432"
  mq:
    image: rabbitmq:3-management
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    restart: "always"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"
  flower:
    image: mher/flower
    command: --broker=amqp://guest:guest@mq:5672/ --broker_api=http://guest:guest@mq:15672/api/
    ports:
      - "5555:5555"

