{% include 'misc/header.py' -%}
#
# Base image Dockerfile for {{cookiecutter.project_shortname}} application.
#
# This image installs all Python dependencies for your application. It's based
# on CentOS 7 with Python 3 (https://github.com/inveniosoftware/docker-invenio)
# and includes Pip, Pipenv, Node.js, NPM and some few standard libraries
# Invenio usually needs.

FROM inveniosoftware/centos7-python:3.6
COPY Pipfile Pipfile.lock ./
RUN pipenv install --deploy --system
