version: '2.1'
services:
  # Application
  web:
    extends:
      file: docker-services.yml
      service: app
    command: invenio run -h 0.0.0.0 -p 5000
    environment:
      - "FLASK_DEBUG=1"
      - "INVENIO_SESSION_COOKIE_SECURE=False"
    ports:
      - "5000:5000"
    links:
      - cache
      - es
      - mq
      - db
  # Worker
  worker:
    extends:
      file: docker-services.yml
      service: app
    restart: "always"
    command: "celery worker -A invenio_app.celery --loglevel=INFO"
    links:
      - cache
      - es
      - mq
      - db
  # Monitoring
  flower:
    extends:
      file: docker-services.yml
      service: flower
    links:
      - mq
  # Base services
  cache:
    extends:
      file: docker-services.yml
      service: cache
  db:
    extends:
      file: docker-services.yml
      service: db
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    extends:
      file: docker-services.yml
      service: es
