#!/usr/bin/env bash
{% include 'misc/header.py' %}
set -e

pip install -r requirements.txt
pip install -e .[all]

npm update && npm install --silent -g node-sass@4.9.0 clean-css@3.4.19 uglify-js@2.7.3 requirejs@2.2.0

CWD=`pwd`
invenio npm
python_prefix=$(python -c "import sys; print(sys.prefix)")
cd ${1-$python_prefix}/var/instance/static
npm install
cd ${CWD}
invenio collect -v
invenio assets build
