#!/usr/bin/env bash
{% include 'misc/header.py' %}
set -e

pip install -e .[all]

npm update && npm install --silent -g node-sass@3.8.0 clean-css@3.4.19 uglify-js@2.7.3 requirejs@2.2.0

CWD=`pwd`
invenio npm
cd ${VIRTUAL_ENV}/var/instance/static
npm install
cd ${CWD}
invenio collect -v
invenio assets build
