#!/usr/bin/env bash
{% include 'misc/header.py' %}
set -e

script_path=$(dirname "$0")
invenio run --cert "$script_path"/../docker/nginx/test.crt \
            --key "$script_path"/../docker/nginx/test.key \
