#!/usr/bin/env bash
{% include 'misc/header.py' %}
set -e

docker-compose  up -d

# TODO: Clean redis

invenio db destroy --yes-i-know
invenio db init create
curl -XDELETE localhost:9200/*
invenio index init --force
invenio index queue init

# Create admin role to rectict access
invenio users create test@test.ch -a --password=123456
invenio users create admin@test.ch -a --password=123456
invenio roles create admin
invenio roles add admin@test.ch admin
invenio access allow superuser-access role admin
