#!/usr/bin/env bash
{% include 'misc/header.py' %}
set -e

docker-compose  up -d

docker/wait-for-services.sh

# TODO: Clean redis

invenio db destroy --yes-i-know
invenio db init create
curl -XDELETE localhost:9200/*
invenio index init --force
invenio index queue init

# Create admin role to rectict access
invenio roles create admin
invenio access allow superuser-access role admin
