name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * 6'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
          cookiecutter-database: [postgresql, mysql]
          cookiecutter-elasticsearch: [6, 7]
          e2e: [no]
          experimental: [false]

          include:
          - cookiecutter-database: postgresql
            cookiecutter-elasticsearch: 7
            experimental: true
            E2E: yes

          - cookiecutter-database: mysql
            cookiecutter-elasticsearch: 7
            experimental: true
            E2E: yes

    env:
      # TODO: Adapt EXTRAS accordingly
      # Cookiecutter configuration
      COOKIECUTTER_DATABASE: ${{ matrix.cookiecutter-database }}
      COOKIECUTTER_ELASTICSEARCH: ${{ matrix.cookiecutter-elasticsearch }}
      # Force pipenv to create a new virtualenv to bypass travis virtualenv.
      PIPENV_IGNORE_VIRTUALENVS: 1
      PIPENV_PYUP_API_KEY: ""
      # E2E tests config
      # Print screenshots to console output
      E2E_OUTPUT: base64
      # Enable end-to-end tests
      E2E: ${{ matrix.E2E }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          if [ ${E2E} == 'yes' ] && [ ! -f $HOME/webdrivers/chromedriver ]; then wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -P $HOME/webdrivers; unzip -d $HOME/webdrivers $HOME/webdrivers/chromedriver_linux64.zip; fi
          pip install --upgrade pip setuptools py pipenv
          pip install cookiecutter twine wheel coveralls sphinx

      - name: Run tests
        run: |
          export DISPLAY=:99.0
          if [ ${E2E} == 'yes' ]; then sh -e /etc/init.d/xvfb start; sleep 3; fi
          ./run-tests.sh
